coverage:
  status:
    project:
      default:
        target: 80%
    patch:
      default:
        target: 80%

ignore:
  - "**/R"
  - "**/R_*"
  - "**/di/**"
  - "**/util/**"
  - "**/logging/**"
  - "**/BuildConfig*"
  - "**/Manifest*"
  - "com/sanaa/novix/ui/theme/**"
  - "**/ComposableSingletons*"
  - "**/MainActivity*"
  - "**/NovixApp*"
  - "com/sanaa/image_viewer/**"
  - "com/sanaa/designsystem/**"
  - "com/sanaa/search/dto/**"
  - "com/sanaa/search/di/**"
  - "**/entity/**"
  - "search/usecase/search_param/**"
  - "**/dao/**"
  - "**/dto/**"
  - "**/db/**"
  - "**/response/**"
  - "**/exceptions/**"
  - "com/sanaa/search/dataSource/**"
  - "com/sanaa/identity/dataSoruce/dataStore/**"
  - "com/sanaa/vod/mapper/**"
  - "com/sanaa/search/repository/**"
  - "com/sanaa/presentation/screen/componants/**"
  - "com/sanaa/presentation/component/**"
  - "com/sanaa/presentation/model/**"
  - "com/sanaa/presentation/details_base/**"
  - "com/sanaa/presentation/screen/state/**"
  - "com/sanaa/presentation/screen/SearchScreen*"
  - "com/sanaa/vod/media/movie/MovieApiService/*",

  - "com/sanaa/presentation/navigation/**"
  - "**/proto/**"
  - "**/mapper/**"
  - "com/sanaa/presentation/**"
  - "com/sanaa/presentation/screen/actor/componants/**"
  - "com/sanaa/presentation/screen/actor/screen/**"
  - "com/sanaa/presentation/screen/episodeDetails/components/**"
  - "com/sanaa/presentation/screen/episodeDetails/**"
  - "com/sanaa/presentation/screen/movieDetails/components/**"
  - "com/sanaa/presentation/screen/genreMovies/**"
  - "com/sanaa/presentation/screen/movieDetails/MovieDetailsScreen*"
  - "com/sanaa/presentation/screen/genreTvShows/GenreTvShowsScreen*"
  - "com/sanaa/presentation/screen/review/components/**"
  - "com/sanaa/presentation/screen/review/**"
  - "com/sanaa/presentation/screen/series/components/**"
  - "com/sanaa/presentation/screen/series/SeriesScreen*"
  - "com/sanaa/feature/media_details/api/*"
  - "com/sanaa/presentation/cards/**"
  - "feature/media_details/api**",
  - "com/sanaa/presentation/cards/**",
  - "com/sanaa/presentation/components/**",
  - "com/sanaa/presentation/app/**",
  - "com/sanaa/presentation/api/**",
  - "com/sanaa/presentation/screen/**",
  - "com/sanaa/vod/dataSource/remote/search/search/**",
  - "com/sanaa/presentation/util/**",
  - "com/sanaa/presentation/state/**",
  - "com/sanaa/vod/media/**",
  - "com/sanaa/presentation/modifier/**",

  - "com/sanaa/presentation/screen/login/**"
  - "**/network/**"
  - "com/sanaa/identity/dataSoruce/local/dataStore/**"
  - "**/util/**"
  - "com/sanaa/presentation/screen/login/components/**"
  - "com/sanaa/presentation/screen/login_base/**"
  - "com/sanaa/presentation/screen/welcome/**"
  -
  - "com/sanaa/presentation/screen/welcome/components/**"
  - "**/api/**",
