coverage:
  status:
    project:
      default:
        target: 80%
    patch:
      default:
        target: 80%

ignore:
  - "**/R"
  - "**/R_*"
  - "**/di/**"
  - "**/logging/**"
  - "**/BuildConfig*"
  - "**/Manifest*"
  - "com/sanaa/novix/ui/theme/**"
  - "**/ComposableSingletons*"
  - "**/MainActivity*"
  - "**/NovixApp*"
  - "com/sanaa/image_viewer/**"
  - "com/sanaa/designsystem/**"
  - "com/sanaa/search/dto/**"
  - "com/sanaa/search/di/**"
  - "**/entity/**"
  - "search/usecase/search_param/**"
  - "**/dao/**"
  - "**/dto/**"
  - "**/response/**"
  - "**/exceptions/**"
  - "com/sanaa/search/dataSource/**"
  - "com/sanaa/search/mapper/**"
  - "com/sanaa/search/repository/**"
  - "com/sanaa/presentation/filter_bottomsheet/components/**"
  - "com/sanaa/presentation/screen/componants/**"
  - "com/sanaa/presentation/component/**"
  - "com/sanaa/presentation/model/**"
  - "com/sanaa/presentation/details_base/**"
  - "com/sanaa/presentation/screen/state/**"
  - "com/sanaa/presentation/screen/SearchScreen*"
  - "com/sanaa/presentation/filter_bottomsheet/FilterBottomSheet*"
  - "com/sanaa/search/search_result/db/**"
  - "com/sanaa/vod/media/movie/MovieApiService/*",

  - "com/sanaa/presentation/navigation/**"
  - "com/sanaa/presentation/screen/actor/componants/**"
  - "com/sanaa/presentation/screen/actor/screen/**"
  - "com/sanaa/presentation/screen/episode_details/components/**"
  - "com/sanaa/presentation/screen/episode_details/**"
  - "com/sanaa/presentation/screen/movie_details/components/**"
  - "com/sanaa/presentation/screen/movie_categories/**"
  - "com/sanaa/presentation/screen/movie_details/MovieDetailsScreen*"
  - "com/sanaa/presentation/screen/review/components/**"
  - "com/sanaa/presentation/screen/review/**"
  - "com/sanaa/presentation/screen/series/components/**"
  - "com/sanaa/presentation/screen/series/SeriesScreen*"
  - "com/sanaa/feature/media_details/api/*"
  - "com/sanaa/presentation/cards/**"
