name: CI - Test Coverage Check

on:
  pull_request:
    branches:
      - development

jobs:
  test-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Grant execute permission for Gradlew
        run: chmod +x ./gradlew

      - name: Run tests with coverage
        run: ./gradlew :app:testDebugUnitTest :app:jacocoTestReport


      - name: Check if coverage is >= 80%
        run: |
          MISSED=$(grep -oPm1 "(?<=<counter type=\"LINE\" missed=\")[^\"]+"  app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml)
          COVERED=$(grep -oPm1 "(?<=<counter type=\"LINE\" covered=\")[^\"]+"  app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml)
          TOTAL=$(awk -v m=$MISSED -v c=$COVERED 'BEGIN {print m + c}')
          PERCENT=$(awk -v m=$MISSED -v c=$COVERED 'BEGIN {print (c / (c + m)) * 100}')
          echo "Line coverage is $PERCENT%"
          THRESHOLD=80
          RESULT=$(awk -v p=$PERCENT -v t=$THRESHOLD 'BEGIN {print (p < t)}')
          if [[ $RESULT == 1 ]]; then
            echo "Coverage below 80%!"
            exit 1
          else
            echo "Coverage passed with $PERCENT%"
          fi
