name: CI - Test Coverage Check

on:
  pull_request:
    branches: [main, development]

jobs:
  test-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant permission for Gradle
        run: chmod +x ./gradlew

      - name: Run Unit Tests with Kover Coverage
        run: ./gradlew test koverVerify koverXmlReport koverHtmlReport

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: build/reports/kover/merged/report.xml
          flags: unittests
          name: novix-coverage-report